### ISSUE TITLE
Error in parsing PeriodicTable 

### ISSUE THREAD

**Issue by ttustonic** [dbaileychess/CSMSL#1]
There is an error in the method Load(string filePath) in the PeriodicTable.cs, line 105.
Calls to double.Parse(...) should include a InvariantCulture parameter, like this
`double mass = double.Parse(reader["Mass"], System.Globalization.CultureInfo.InvariantCulture);`
Without this all the parsed values are wrong when the local number format uses comma instead of dot for a decimal separator.

This fix should probably be applied to all calls to double.Parse and float.Parse.

**Comment by dbaileychess** [comment]
Thanks for the report

Closed: a898658ddc69076425ff1afa63ecc745a8fd0de1

**Comment by ttustonic** [comment]
Hello!
Sorry to open this again, but it should be InvariantCulture, not CurrentCulture. For example, German and Croatian culture use comma (,) for a decimal separator.
